### ISSUE TITLE
OOS language pack example

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/OfficeOnlineServerDsc#11]
Try to prepare machine with OOS binaries: installed OOS + Language Pack + CU.
Is there any good example for installing Language packs? What I encountered is that the language pack on the downloads web site is exe file: https://www.microsoft.com/sv-SE/download/details.aspx?id=51963. However, in the OfficeOnlineServerInstallLanguagePack resource I'm supposed to provide "Path to folder that contains the setup.exe"
https://github.com/PowerShell/OfficeOnlineServerDsc/wiki/OfficeOnlineServerInstallLanguagePack.

Should I provide path for general OOS installation media and language pack files are download from the site automatically by DSC? How should I use this?

**Comment by NikCharlebois** [comment]
Hi @shurick81 you will need to extract the content of the language pack first (e.g. wacserverlanguagepack.exe /extract:c:\temp). I will update the documentation to better reflect this
