### ISSUE TITLE
OOS Language pack module

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/OfficeOnlineServerDsc#13]
**Details of the scenario you try and problem that is occurring:**
Trying to install OOS binaries with a language pack.

When I complile, I get the following error:
```
At C:\Projects\Unionen_Intranet_SharePoint2016Upgrade\SPUpgrade\DSC\OOSInstall.ps1:7 char:5
+     OfficeOnlineServerInstallLanguagePack CurrentLanguagePack
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Undefined DSC resource 'OfficeOnlineServerInstallLanguagePack'. Use Import-DSCResource to import the resource.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ResourceNotDefined
```

**The DSC configuration that is using the resource:**
```
Configuration Example 
{
    param()

    Import-DscResource -ModuleName OfficeOnlineServerDsc

    OfficeOnlineServerInstallLanguagePack CurrentLanguagePack
    {
        Ensure = "Present"
        BinaryDir = "D:\"
        Language = "fr-fr"
    }
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 10,

```
PS C:\Projects\Unionen_Intranet_SharePoint2016Upgrade\SPUpgrade> $PSVersionTable.PSVersion.ToString()
5.1.14393.1770
```

**Version of the DSC module you're using:**
```
PS C:\Projects\Unionen_Intranet_SharePoint2016Upgrade\SPUpgrade> Find-Module OfficeOnlineServerDsc

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.0.0.0    OfficeOnlineServerDsc               PSGallery            The OfficeOnlineServerDsc module provides the ability to install Office Online Server (formerly
```

**Comment by NikCharlebois** [comment]
It looks like you are using version 1.0.0.0 from the gallery which doesn’t include the OOSDSCLP resource. You will need to download it from GitHub instead. LanguagePack support will only hit Release in the Gallery on December 20th. You can have a look at the following blog post to get more info. Just make sure you get the version from GitHub and not the gallery http://nikcharlebois.com/deploy-an-office-online-server-environment-using-powershell-dsc/

**Comment by shurick81** [comment]
Thank you Nik. is it this one you mean? https://github.com/PowerShell/OfficeOnlineServerDsc/blob/dev/Modules/OfficeOnlineServerDsc/DSCResources/MSFT_OfficeOnlineServerInstallLanguagePack/MSFT_OfficeOnlineServerInstallLanguagePack.psm1 
Test-TargetResource looks as a mockup now.

I think I will grab the most from this code and implement it temporary via Script DSC resource and then I will refactor it when the version 1.1.0.0 is available in the gallery. Thank you for your contribution!

**Comment by NikCharlebois** [comment]
That is the current file. The Test-TargetResource calls into the Get-TargetResource which will return information about the installed language pack (if any). Test-TargetResource then returns $true if it was detected or $false otherwise. It is the complete function. You should be good by using it as is

**Comment by shurick81** [comment]
Ah, I see, thank you!
