### ISSUE TITLE
Undefined DSC resource 'OfficeOnlineServerWebAppsFarm'

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/OfficeOnlineServerDsc#14]
**Details of the scenario you try and problem that is occurring:**
Trying to build a farm. I get this error:
```
At C:\Projects\Unionen_Intranet_SharePoint2016Upgrade\SPUpgrade\DSC\OOSFarm.ps1:10 char:5
+     OfficeOnlineServerWebAppsFarm Farm
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Undefined DSC resource 'OfficeOnlineServerWebAppsFarm'. Use Import-DSCResource to import the resource.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ResourceNotDefined
```

**The DSC configuration that is using the resource:**
```
Configuration OOSFarm 
{
    param(
        $mainParameters
    )

    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName OfficeOnlineServerDsc -ModuleVersion 1.0.0.0
    
    OfficeOnlineServerWebAppsFarm Farm
    {
        InternalURL    = "https://$($mainParameters.OOSHostName)"
        EditingEnabled = $true
    }

}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2016
PSVersion                      5.1.14393.1770

**Version of the DSC module you're using:**
1.0.0.0

**Comment by andikrueger** [comment]
With version 1.0.0.0 there are several naming changes. Have a look into the [changelog](https://github.com/PowerShell/OfficeOnlineServerDsc/blob/release-1.0/CHANGELOG.md). 

OfficeOnlineServerWebAppsFarm becomes OfficeOnlineServerFarm
OfficeOnlineServerWebAppsMachine becomes: OfficeOnlineServerMachine

**Comment by NikCharlebois** [comment]
As @andikrueger points out, you will need to modify your script as follow:
[...]
OfficeOnlineServerFarm Farm
    {
        InternalURL    = "https://$($mainParameters.OOSHostName)"
        EditingEnabled = $true
    }
[...]
