### ISSUE TITLE
Binarydir needs to be marked as key in Language Pack Resource

### ISSUE THREAD

**Issue by NikCharlebois** [dsccommunity/OfficeOnlineServerDsc#17]
**Details of the scenario you try and problem that is occurring:**
The BinaryDir parameter needs to be marked as a Key in the Language Pack resources, otherwise you can only ever install one LP with DSC.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016 WMF 5.1

**Version of the DSC module you're using:**
1.1.0.0

**Comment by ykuijs** [comment]
Implemented, issue can be closed
