### ISSUE TITLE
Wrong resource name OfficeOnlineServerWebAppsMachine

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/OfficeOnlineServerDsc#28]
**Details of the scenario you try and problem that is occurring:**
Building multi-server OOS farm.
getting error that the term OfficeOnlineServerWebAppsMachine does not exist.
**The DSC configuration that is using the resource:**
```
            OfficeOnlineServerWebAppsMachine JoinFarm
            {
                MachineToJoin   = $firstOOSNode
                Roles           = "All"
            }
```
The one above does not work. The one below does:
```
            OfficeOnlineServerMachine JoinFarm
            {
                MachineToJoin   = $firstOOSNode
                Roles           = "All"
            }
```
Apparently, Wiki doc should be fixed.
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016, WMF 5.1
**Version of the DSC module you're using:**
1.2.0.0

**Comment by johlju** [comment]
@NikCharlebois are there manual process to update the Wiki?

**Comment by NikCharlebois** [comment]
Documentation updated
