### ISSUE TITLE
OfficeOnlineServerInstall fails from non NTFS filesystems

### ISSUE THREAD

**Issue by pessimism** [dsccommunity/OfficeOnlineServerDsc#49]
#### Details of the scenario you tried and the problem that is occurring
Use OfficeOnlineServerInstall pointing to a non-NTFS filesystem such as a mounted ISO image.  The routine tries to check for the zone.identifier alternate NTFS data stream, fails, and throws an error which causes the DSC routine to report that it was unsuccessful and installation does not proceed.
#### Verbose logs showing the problem
"The parameter is incorrect" from GetItem
#### Suggested solution to the issue
Rework offending code located here:
https://github.com/PowerShell/OfficeOnlineServerDsc/blob/1e7be17f930613e9211641945a78717f228c31cc/Modules/OfficeOnlineServerDsc/DSCResources/MSFT_OfficeOnlineServerInstall/MSFT_OfficeOnlineServerInstall.psm1#L34

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        OfficeOnlineServerInstall InstallBinaries
        {
            Path      = "$($oosSourceLetter):\$($oosSourceDirectory)\setup.exe"
            Ensure    = "Present"
            DependsOn = @('[WindowsFeature]Web-Server',
                          '[WindowsFeature]Web-Mgmt-Tools',
                          '[WindowsFeature]Web-Mgmt-Console',
                          '[WindowsFeature]Web-WebServer',
                          '[WindowsFeature]Web-Common-Http',
                          '[WindowsFeature]Web-Default-Doc',
                          '[WindowsFeature]Web-Static-Content',
                          '[WindowsFeature]Web-Performance',
                          '[WindowsFeature]Web-Stat-Compression',
                          '[WindowsFeature]Web-Dyn-Compression',
                          '[WindowsFeature]Web-Security',
                          '[WindowsFeature]Web-Filtering',
                          '[WindowsFeature]Web-Windows-Auth',
                          '[WindowsFeature]Web-App-Dev',
                          '[WindowsFeature]Web-Net-Ext45',
                          '[WindowsFeature]Web-Asp-Net45',
                          '[WindowsFeature]Web-ISAPI-Ext',
                          '[WindowsFeature]Web-ISAPI-Filter',
                          '[WindowsFeature]Web-Includes',
                          '[WindowsFeature]Windows-Identity-Foundation',
                          '[File]oosinstaller')
        }
```

#### The operating system the target node is running
Windows Server 2016

#### Version and build of PowerShell the target node is running
5.1
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.4.0

**Comment by ykuijs** [comment]
Fixed via PR #47
