### ISSUE TITLE
OfficeOnlineServerDsc: Converting to new CI pipeline

### ISSUE THREAD

**Issue by johlju** [dsccommunity/OfficeOnlineServerDsc#50]
Work need to be done to convert this repository to use the new CI pipeline.

https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/

**Comment by ykuijs** [comment]
Am going to work on this!

**Comment by johlju** [comment]
Cool!

**Comment by johlju** [comment]
This has been resolved
