### ISSUE TITLE
DSC Configuration Error installing OOS in Azure

### ISSUE THREAD

**Issue by FloFi17** [dsccommunity/OfficeOnlineServerDsc#8]
Details of the scenario you try and problem that is occurring:
I try to Install an Office Online Server in Azure. After provisioning the Server, the dsc Extension is added to the Server and results in the following error:
_DSC Configuration completed with error(s). Following are the first few: The term 'New-OfficeWebAppsFarm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._

If I start the deployment again, it runs successfully. I can also wait for the next automatically dsc consistency check, it also runs successfully. This is bad for azure deployment because of dependencies.
My plan is to connect the sharepoint automatically to Office Online Server after successfully Installation.  

The DSC configuration that is using the resource:
configuration InitializeOfficeOnlineServer
{
Node localhost
    {
        LocalConfigurationManager
        {
            ConfigurationMode = 'ApplyOnly'
            RebootNodeIfNeeded = $true
        }
   $requiredFeatures = @(
            "Web-Server",
            "Web-Mgmt-Tools",
            "Web-Mgmt-Console",
            "Web-WebServer",
            "Web-Common-Http",
            "Web-Default-Doc",
            "Web-Static-Content",
            "Web-Performance",
            "Web-Stat-Compression",
            "Web-Dyn-Compression",
            "Web-Security",
            "Web-Filtering",
            "Web-Windows-Auth",
            "Web-App-Dev",
            "Web-Net-Ext45",
            "Web-Asp-Net45",
            "Web-ISAPI-Ext",
            "Web-ISAPI-Filter",
            "Web-Includes",
            "NET-Framework-Features",
            "NET-Framework-45-Features",
            "NET-Framework-Core",
            "NET-Framework-45-Core",
            "NET-HTTP-Activation",
            "NET-Non-HTTP-Activ",
            "NET-WCF-HTTP-Activation45",
            "Windows-Identity-Foundation",
            "Server-Media-Foundation"
            )

        foreach ($feature in $requiredFeatures)
        {
            WindowsFeature "WindowsFeature-$feature"
            {
                Ensure = 'Present'
                Name   = $feature
            }
        }

        $prereqDependencies = $RequiredFeatures | ForEach-Object -Process {
            return "[WindowsFeature]WindowsFeature-$_"
        }
        OfficeOnlineServerInstall InstallBinaries
        {
            Ensure    = "Present"
            Path      = "F:\_Install\OOS\setup.exe"
            DependsOn = $prereqDependencies
        }
        OfficeOnlineServerFarm LocalFarm
        {
            InternalURL    = $OOSURL
            ExternalURL    = $OOSURL
            LogLocation    = "G:\Logs\ULS"
            EditingEnabled = $true
            AllowHttp      = $true
            DependsOn      = "[OfficeOnlineServerInstall]InstallBinaries"
        }
    }
}

Version of the Operating System and PowerShell the DSC Target Node is running: 
Windows Server 2016 Datacenter (Azure Standard Template)

Version of the DSC module you're using: 
1.0.0.0

**Comment by henryallsworth** [comment]
FloFi17, I've been struggling with this same issue for about a week and came up with a shortcut on how to fix.  I looked into some older version of the code from before they changed the function names and could see that they were manually loading the module for each function.  I modified the MSFT_OfficeOnlineServerFarm.psm1 file added "Import-Module “F:\Program Files\Microsoft Office Web Apps\AdminModule\OfficeWebApps\OfficeWebApps.psd1” -ErrorAction Stop" at line 395.  I have my OOS installation in a custom folder and hard coded it to that path for the short term.  With this I was able to move forward.
Hope this helps.

**Comment by FloFi17** [comment]
Thank you @henryallsworth. This worked for me too.
 I added the full path to the get, set and test functions in the Module  MSFT_OfficeOnlineServerFarm.psm1.

`Import-Module “C:\Program Files\Microsoft Office Web Apps\AdminModule\OfficeWebApps\OfficeWebApps.psd1" -ErrorAction Stop`

 Now I can install an complete SharePoint Environment with Office Online Server.

**Comment by NikCharlebois** [comment]
Glad you figured out your problem. I am just going to add that OOS in Azure is only supported by your license agreement if it is dedicated to your customer
https://support.microsoft.com/en-us/help/3199955/office-web-apps-and-office-online-server-supportability-in-azure
Thanks folks
